services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    container_name: pelican_panel
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "8089:80"
    volumes:
      - /appdata/pelican/panel/data:/pelican-data
      - /appdata/pelican/panel/logs:/var/www/html/storage/logs
    environment:
      TZ: America/Chicago
      APP_TIMEZONE: America/Chicago
      APP_ENV: production
      APP_URL: ${PELICAN_HOST}
      ADMIN_EMAIL: ${EMAIL}
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
