services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "4080:80"
      - "4443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /appdata/pelican/panel/data:/pelican-data
      - /appdata/pelican/panel/logs:/var/www/html/storage/logs
    environment:
      XDG_DATA_HOME: /pelican-data
      APP_URL: ${PELICAN_HOST}
      ADMIN_EMAIL: ${EMAIL}

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
