site_name: My Docs
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: grey

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: pink
      accent: grey

  features:
    - navigation.sections
    - navigation.instant

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
