services:
  expenseowl:
    image: tanq16/expenseowl:main
    container_name: expenseowl
    restart: unless-stopped
    ports:
      - "5001:8080"
    volumes:
      - /appdata/expenseowl:/app/data
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
