services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=America/Chicago
      - REDIS_URL=redis://redis:6379
    volumes:
      - /appdata/yamtrack:/yamtrack/db
    ports:
      - "8005:8000"
    networks:
      - reitenth-network

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - /appdata/yamtrack/redis:/data
    networks:
      - reitenth-network
      
networks:
  reitenth-network:
    external: true
