services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /appdata/jellyfin:/config
      - /data/media:/data/media
      - /data/posters:/gdrive
    ports:
      - 8096:8096
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`reitenth.org`)"
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
