services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - /appdata/glance/config:/app/config
      - /appdata/glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8010:8080
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
