services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '1180:80'
      - '81:81'
      - '11443:443'
    volumes:
      - /appdata/nginxproxymanager:/data
      - /appdata/nginxproxymanager/letsencrypt:/etc/letsencrypt
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
