services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /appdata/code-server:/config
      - /data/projects:/projects
      - /appdata:/appdata
      - /data/docker:/docker
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
