services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
      - DOCKER_MODS=linuxserver/mods:universal-docker|linuxserver/mods:code-server-python3
    volumes:
      - /appdata/code-server:/config
      - /data/github:/github
      - /appdata:/appdata
      - /data/docker:/docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7443:8443
    restart: unless-stopped
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
