services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /appdata/vaultwarden/:/data/
    ports:
      - 2080:80
    networks:
      - reitenth-network
networks:
  reitenth-network:
    external: true
